### ISSUE TITLE
Font ProgressEngine, Missing Letters h & H

### ISSUE THREAD

**Issue by MickyB** [MagicSetEditorPacks/Full-Magic-Pack#1]
![38d7d7eb845b56943ee51f35a515f0b0](https://user-images.githubusercontent.com/12384196/154206526-e13affdf-3339-4ae1-9388-47818d340a25.png)

after installing the Font, used ProgressEngine & noticed h & H were missing in the font, not sure if missing letters are intentionally missing (they don't exist) or intentional

**Comment by CajunAvenger** [comment]
ProgressEngine isn't maintained by me so there's not really anything I can do here. Doesn't seem to be on GitHub so the best I can offer is say try GuruJ_ who updates it over at [the Phyrexian Language subreddit.](https://www.reddit.com/r/PhyrexianLanguage/)
