### ISSUE TITLE
Ravnica Watermarks in Mainframe are looking for nonexistent images, the names are wrong.

### ISSUE THREAD

**Issue by crushcastles23** [MagicSetEditorPacks/Full-Magic-Pack#57]
![image](https://github.com/user-attachments/assets/1376ba0c-9808-4acc-bbed-b304e9c6e234)

They're formatted as `watermark_guild#.png` in the download, but the frame is looking for just `guild#.png`

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
fixed in #18
