### ISSUE TITLE
Options to rename

### ISSUE THREAD

**Issue by CajunAvenger** [MagicSetEditorPacks/Full-Magic-Pack#63]
I've gotten a website working that will let users upload a mse file and apply patches to it, meaning we can rename fields with less of a headache. Looking for things that should get renamed

Card Fields
* promote extra card fields to card fields; in particular the Lesson/transform symbol moving to Transformation
* standardize popout image (sometimes its image 2, sometimes its mainframe image: mainframe image should probably be renamed too)

Set Fields
* rename `alias as cardname` to `CARDNAME replacement`
* adjust old `blended watermarks` to the new one
* `shorten types for rarity` to `display rarity symbols`

Styling Fields
* possibly combine M15 Mainframe's chops into one field
* finally remove the duplicate Clear on Mainframe Planeswalker
* clean up the Mainframe DFC level offsets, the backwardsness and the many unneeded slots post planeswalker update
* change Chapter Coordinates to Snap chapter to box
* move holofoil stamped rares & color indicator dot over to the card fields

Templates
* theoretically we could even rename m15-altered and m15-split-fusable to m15-mainframe and m15-mainframe-splits and so on

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
Also clean the DFC card fields. Currently for example, the back face walkers use `card.level_5_text` to `card.level_8_text`. It would be better if 1 to 8 was always reserved for the front face, and 9 to 16 for the back face. This also applies to pt, level arrows, etc...
